name: Close issues on archived repository
on:
  schedule:
    - cron:  '30 2 * * 0'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 7
          stale-issue-label: "dormant"
          stale-issue-message: |
            This issue has being marked as dormant because ${{ github.event.repository.name }} is being archived. The code is now part of the main [BlobToolKit repository](https://github.com/blobtoolkit/blobtoolkit).
          
            If you feel the issue has not been resolved, please follow the updated BlobToolKit [installation instructions](https://blobtoolkit.genomehubs.org/install) to first confirm that you are using the latest version, and then open a [new issue at the main BlobToolKit repository](https://github.com/blobtoolkit/blobtoolkit/issues) if necessary.

            This issue will be automatically closed in 7 days.
          close-issue-message: This issue was closed because it has been inactive for 7 days since being marked as dormant.
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
